#!/bin/sh

DIST="$1"
FROM=

case "$DIST" in
	debian10|buster|stable)
		DIST="debian10"
		FROM="debian:10"
		;;
	ubuntu20.04|focal)
		DIST="ubuntu20.04"
		FROM="ubuntu:20.04"
		;;
	ubuntu18.04|bionic)
		DIST="ubuntu18.04"
		FROM="ubuntu:18.04"
		;;
	*)
		echo "Unknown distribution: $DIST"
		exit 1
		;;
esac


cat > Dockerfile.init << EOF
FROM ${FROM}

ENV DEBIAN_FRONTEND=noninteractive

RUN echo 'Acquire::http::Proxy "http://::1:3142";' > /etc/apt/apt.conf.d/01-proxy

RUN echo 'deb http://psha.org.ru/debian $DIST contrib backports' > /etc/apt/sources.list.d/psha.org.ru.list
COPY pubkey.gpg /etc/apt/trusted.gpg.d/psha.org.ru.gpg

RUN apt update
RUN apt install --yes --no-install-recommends build-essential fakeroot ccache
EOF

docker build --network host --tag build:${DIST} --file Dockerfile.init .
