#!/usr/bin/perl

use strict;
use warnings;

use Dpkg::Control::Info;
use Dpkg::Deps;
use File::Temp;

my $dist = $ARGV[0] || "ubuntu20.04";

my $control = Dpkg::Control::Info->new();

my $dir = File::Temp->newdir();

my $pkg = $control->get_source->{'Source'};
my $tag = "build-tmp:${pkg}-${dist}";
my $version = qx/git describe --tags/;
$version =~ s/\n//g;
$version =~ s/^v//;
$version =~ s,^debian/,,;

if (!system("git show-ref pristine-tar")) {
	my @utags = [];
	foreach (split(/\n/, qx,git tag -l 'upstream/*',)) {
		$_ =~ s,^upstream/,,;
		if (substr($version, 0, length($_) + 1) eq ($_ . '-')) {
			system("pristine-tar checkout $dir/${pkg}_$_.orig.tar.gz") and die("Failed to checkout pristine tar");
		}
	}
	$version .= "~${dist}";
} else {
	$version .= "+${dist}";
}

system("git clone . $dir/src");
system("dch -b -v $version -m 'Build version bump' -D unstable -c $dir/src/debian/changelog") and die("Failed to bump version to $version");
system("timeout", "600", "docker", "run", "--net=none"
	, "--mount=type=bind,src=$ENV{'HOME'}/.ccache/,dst=/ccache"
	, "--env=CCACHE_DIR=/ccache"
	, "--env=DEB_BUILD_PROFILES=$ENV{'DEB_BUILD_PROFILES'}"
	, "--env=DEB_BUILD_OPTIONS=$ENV{'DEB_BUILD_OPTIONS'}"
	, "--sysctl=net.ipv6.conf.all.disable_ipv6=0"
	, "-w$dir/src"
	, "-v$dir:$dir"
	, "--user=$>"
	, "$tag", "dpkg-buildpackage", "-rfakeroot", "-uc", "-us", "-sa", "-j4");

mkdir("result");
system("cp -av $dir/*.* result/");

#system("docker rmi ${tag}");
