#!/bin/sh

DIST="$1"
FROM=

case "$DIST" in
	debian11|bullseye|stable)
		DIST="debian11"
		FROM="debian:11"
		NAME="buillseye"
		;;
	debian10|buster|oldstable)
		DIST="debian10"
		FROM="debian:10"
		NAME="buster"
		;;
	ubuntu24.04|noble)
		DIST="ubuntu24.04"
		FROM="ubuntu:24.04"
		;;
	ubuntu22.04|jammy)
		DIST="ubuntu22.04"
		FROM="ubuntu:22.04"
		;;
	ubuntu20.04|focal)
		DIST="ubuntu20.04"
		FROM="ubuntu:20.04"
		NAME="focal"
		;;
	ubuntu18.04|bionic)
		DIST="ubuntu18.04"
		FROM="ubuntu:18.04"
		NAME="bionic"
		;;
	*)
		echo "Unknown distribution: $DIST"
		exit 1
		;;
esac


cat > Dockerfile.init << EOF
FROM ${FROM}

ENV DEBIAN_FRONTEND=noninteractive

RUN echo 'Acquire::http::Proxy "http://::1:3142";' > /etc/apt/apt.conf.d/01-proxy

RUN echo 'deb http://psha.org.ru/debian $DIST contrib backports' > /etc/apt/sources.list.d/psha.org.ru.list
COPY pubkey.gpg /etc/apt/trusted.gpg.d/psha.org.ru.gpg

RUN apt update
RUN apt install --yes --no-install-recommends build-essential fakeroot ccache
EOF


docker build --network host --tag build:${DIST} --file Dockerfile.init --no-cache .
